config/routes.rb
Rails.application.routes.draw do

  resources :fish

  resources :licence_issuers do
    resources :fish_wardens
  end

  resources :countries do
    resources :locations
    resources :fisheries
  end

  resources :body_of_waters

  resources :fishing_areas do
    resources :comments
  end

  devise_for :users
  #root to: 'home#index'
  root to: 'fishing_areas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fishing_area.rb
class FishingArea < ApplicationRecord
  belongs_to :user
  belongs_to :body_of_water
  belongs_to :country
  belongs_to :location
  belongs_to :fishery
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :fish
  #active storage
  has_one_attached :thumbnail, dependent: :detach
  #if user did not attach image
  after_commit :add_default_thumbnail, on:[:create, :update]

  validates :name, length: {minimum:3},presence: true, uniqueness: true

  self.per_page=9

  def optimized_image(image,x,y)
    image.variant(resize_to_fill: [x, y]).processed
  end

  private

  def add_default_thumbnail
    unless thumbnail.attached?
      self.thumbnail.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.jpg")), filename: 'default.jpg' , content_type: "image/jpg")
    end
  end

end

app/controllers/fishing_areas_controller.rb
class FishingAreasController < ApplicationController
  before_action :set_fishing_area, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  before_action :is_owner_or_admin, only: [:edit, :update, :destroy]

  # GET /fishing_areas or /fishing_areas.json
  def index
    @fishing_areas = FishingArea.all.order("views DESC").paginate(page: params[:page])
  end

  # GET /fishing_areas/1 or /fishing_areas/1.json
  def show
    views = @fishing_area.views + 1
    @fishing_area.update(views: views)

    @comments = @fishing_area.comments.paginate(page: params[:page], per_page: 5)
  end

  # GET /fishing_areas/new
  def new
    @fishing_area = FishingArea.new

  end

  # GET /fishing_areas/1/edit
  def edit
    #passing countries because of form
    #@countries = Country.all
  end

  # POST /fishing_areas or /fishing_areas.json
  def create
    @fishing_area = FishingArea.new(fishing_area_params)
    @fishing_area.user = current_user

    respond_to do |format|
      if @fishing_area.save
        format.html { redirect_to @fishing_area, notice: "Fishing area was successfully created." }
        format.json { render :show, status: :created, location: @fishing_area }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fishing_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fishing_areas/1 or /fishing_areas/1.json
  def update

      respond_to do |format|
        if @fishing_area.update(fishing_area_params)
          format.html { redirect_to @fishing_area, notice: "Fishing area was successfully updated." }
          format.json { render :show, status: :ok, location: @fishing_area }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @fishing_area.errors, status: :unprocessable_entity }
        end
      end

  end

  # DELETE /fishing_areas/1 or /fishing_areas/1.json
  def destroy
    @fishing_area.destroy
    respond_to do |format|
      format.html { redirect_to fishing_areas_url, notice: "Fishing area was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fishing_area
      @fishing_area = FishingArea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fishing_area_params
      params.require(:fishing_area).permit(:name, :description, :thumbnail, :body_of_water_id, :country_id, :location_id, :fishery_id, :fish_ids => [])
    end

    def is_owner_or_admin
      unless current_user==@fishing_area.user or current_user.admin?
        redirect_to root_path,  alert: 'Your account does not have access to this page!'
      end
    end
end

app/helpers/fishing_areas_helper.rb
module FishingAreasHelper
end

app/views/fishing_areas/_form.html.erb
<%= simple_form_for(@fishing_area) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :country %>
    <%= f.input :location_id, collection: Country.all.order(:name), as: :grouped_select, group_method: :locations %>
    <%= f.input :fishery_id, collection: Country.all.order(:name), as: :grouped_select, group_method: :fisheries %>
    <%= f.input :description %>
    <%= f.association :body_of_water %>
    <%= f.association :fish, as: :check_boxes %>
    <%= f.input :thumbnail %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fishing_areas/_list_fishing_areas.html.erb
<div class="list-group">
  <% fishing_areas.each_with_index do |fishing_area,i| %>
    <% if i%2 == 0 %>
      <%= link_to fishing_area.name, fishing_area , class: "list-group-item list-group-item-action list-group-item-light" %>
    <% else %>
      <%= link_to fishing_area.name, fishing_area , class: "list-group-item list-group-item-action list-group-item-dark" %>
    <% end %>
  <% end %>
</div>

app/views/fishing_areas/_show_fishing_area_item.html.erb
<div class="row">
  <div class="col-3">
    <h6> <%= title %> </h6>
  </div>
  <div class="col">
    <%= link_to item.to_label , pathf %>
  </div>
</div>

app/views/fishing_areas/_target_fish.html.erb
<div class="row row-cols-1 row-cols-md-6">
  <% fish.each do |f| %>
    <div class="col">
      <%= link_to f.name, fish_path(f.id) %>
    </div>
  <% end %>
</div>

app/views/fishing_areas/edit.html.erb
<h1>Editing Fishing Area</h1>

<%= render 'form', fishing_area: @fishing_area %>

<%= link_to 'Show', @fishing_area %> |
<%= link_to 'Back', fishing_areas_path %>

app/views/fishing_areas/index.html.erb
<div class="container" style="margin-top: 2em">
  <%= will_paginate(@fishing_areas, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  <div class="row row-cols-1 row-cols-md-3">
    <% @fishing_areas.each do |fishing_area| %>
    <div class="col mb-md-4">
      <div class="card h-100 border-primary">
        <img class="card-img-top" src="<%= url_for fishing_area.optimized_image(fishing_area.thumbnail, 220, 180) %>" alt="fishing_area" />
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to fishing_area.name, fishing_area , class: "stretched-link" %>
          </h5>
          <p class="card-text"><%= fishing_area.description.truncate_words(50)  %></p>
          <p class="card-text">
            <small class="text-muted">
                Created <%= time_ago_in_words(fishing_area.created_at) %> by
                <%= fishing_area.user.username %> | <%= pluralize(fishing_area.views, "View") %> | 0 comments
            </small>
          </p>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/fishing_areas/new.html.erb
<h1>New Fishing Area</h1>

<%= render 'form', fishing_area: @fishing_area %>

<%= link_to 'Back', fishing_areas_path %>

app/views/fishing_areas/show.html.erb
<div class="container" style="margin-top: 2em">
  <div class="jumbotron">
    <div class="row align-items-center">
      <div class="col">
        <h1 class="display-4"> <%= @fishing_area.name %> </h1>
      </div>
      <% if current_user==@fishing_area.user or current_user.admin %>
        <div class="col">
            <div class="dropdown  float-right">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Edit/Delete
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Edit #{@fishing_area.name}", edit_fishing_area_path(@fishing_area), class:"dropdown-item" %>
                <%= link_to "Delete #{@fishing_area.name}", @fishing_area, class:"dropdown-item", method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            </div>
        </div>
      <% end %>
    </div>


    <hr class="my-4">
    <div class="media">
      <img class="img-fluid" src="<%= url_for @fishing_area.optimized_image(@fishing_area.thumbnail, 800, 400) %>" alt="fishing_area" width="100%"  />

    </div>

    <div id="accordion">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              Basic Information
            </button>
          </h5>
        </div>
        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">
            <% if @fishing_area.country != nil %>
              <%= render "fishing_areas/show_fishing_area_item", item: @fishing_area.country, title:"Country", pathf: country_path(@fishing_area.country.id) %>
            <% end %>
            <% if @fishing_area.location != nil %>
              <%= render "fishing_areas/show_fishing_area_item", item: @fishing_area.location, title:"Location", pathf: country_location_path(@fishing_area.location.country.id,@fishing_area.location.id) %>
            <% end %>
            <% if @fishing_area.body_of_water != nil %>
              <%= render "fishing_areas/show_fishing_area_item", item: @fishing_area.body_of_water, title:"Body of water", pathf: body_of_water_path(@fishing_area.body_of_water.id) %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingFour">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
              Description
            </button>
          </h5>
        </div>
        <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
          <div class="card-body">
            <p><%= @fishing_area.description%></p>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingTwo">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Fishing licence information
            </button>
          </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
          <div class="card-body">
            <% if @fishing_area.fishery != nil %>
              <%= render "fishing_areas/show_fishing_area_item", item: @fishing_area.fishery, title:"Fishery", pathf: country_fishery_path(@fishing_area.fishery.country.id,@fishing_area.fishery.id) %>
              <% if @fishing_area.fishery.licence_issuer != nil %>
                <%= render "fishing_areas/show_fishing_area_item", item: @fishing_area.fishery.licence_issuer, title:"Licence issuer", pathf: licence_issuer_path(@fishing_area.fishery.licence_issuer.id) %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingThree">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Target fish
            </button>
          </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
          <div class="card-body">
              <%= render "fishing_areas/target_fish", fish: @fishing_area.fish%>
          </div>
        </div>
      </div>
    </div>


    <p class="text-muted text-right">

      Created at <%= @fishing_area.created_at.strftime("%d.%m.%Y %H:%M:%S")%> by <%= @fishing_area.user.username %>
    </p>
  </div>
  <br>
  <div id="comment_pane">
    <%= will_paginate(@comments, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
    <%= will_paginate(@comments, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <%= link_to 'Leave a comment', new_fishing_area_comment_path(@fishing_area), class:'btn btn-outline-primary float-right' %>

  <br>

  </div>