config/routes.rb
Rails.application.routes.draw do

  resources :fish

  resources :licence_issuers do
    resources :fish_wardens
  end

  resources :countries do
    resources :locations
    resources :fisheries
  end

  resources :body_of_waters

  resources :fishing_areas do
    resources :comments
  end

  devise_for :users
  #root to: 'home#index'
  root to: 'fishing_areas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_of_water.rb
class BodyOfWater < ApplicationRecord
enum water_type: [ :river, :lake, :stream, :canal, :sea ]
validates :water_type, presence:true
validates :name, presence:true, length:{maximum: 100}
has_many :fishing_areas

def to_label
  "#{name} #{water_type}"
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :fishing_area
  validates :body, presence:true, length:{maximum: 255}

  
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, length: {minimum:3},presence: true, uniqueness: true
  has_many :fishin_areas
  has_many :locations, dependent: :destroy
  has_many :fisheries, dependent: :destroy


  def to_label
    "#{name}"
  end
end

app/models/fish.rb
class Fish < ApplicationRecord
  has_and_belongs_to_many :fishing_areas
  validates :name, length: {minimum:3,maximum:100},presence: true, uniqueness: true
  validates :latin_name, length: {minimum:3,maximum:100},presence: true, uniqueness: true
  validates :description, length: {maximum:1024}
end

app/models/fish_warden.rb
class FishWarden < ApplicationRecord
  validates :phone, length: {minimum:9, maximum:15},presence: true, uniqueness: true
  validates :name, length: {minimum:1},presence: true
  belongs_to :licence_issuer
end

app/models/fishery.rb
class Fishery < ApplicationRecord
  belongs_to :country
  has_many :fishing_areas
  belongs_to :licence_issuer
  validates :name, length: {minimum:3},presence: true, uniqueness: true

  def to_label
    "#{name}"
  end
end

app/models/fishing_area.rb
class FishingArea < ApplicationRecord
  belongs_to :user
  belongs_to :body_of_water
  belongs_to :country
  belongs_to :location
  belongs_to :fishery
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :fish
  #active storage
  has_one_attached :thumbnail, dependent: :detach
  #if user did not attach image
  after_commit :add_default_thumbnail, on:[:create, :update]

  validates :name, length: {minimum:3},presence: true, uniqueness: true

  self.per_page=9

  def optimized_image(image,x,y)
    image.variant(resize_to_fill: [x, y]).processed
  end

  private

  def add_default_thumbnail
    unless thumbnail.attached?
      self.thumbnail.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.jpg")), filename: 'default.jpg' , content_type: "image/jpg")
    end
  end

end

app/models/licence_issuer.rb
class LicenceIssuer < ApplicationRecord
  validates :name, length: {minimum:3},presence: true, uniqueness: true
  has_many :fisheries
  has_many :fish_wardens

  def to_label
    "#{name}"
  end

end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, length: {minimum:3, maximum:100},presence: true
  validates :province, length: {minimum:3, maximum:100},presence: true
  has_many :fishing_areas
  belongs_to :country

  def to_label
    "#{name}, #{province}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fishing_areas
  has_many :comments, dependent: :destroy

  def username
    email.split("@")[0].capitalize
  end

  def to_label
    username
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :is_admin!,  except: [:index , :show]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:name)
    end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :set_fish, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :is_admin!, except: [:index, :show]

  # GET /fish or /fish.json
  def index
    @fish = Fish.all
  end

  # GET /fish/1 or /fish/1.json
  def show
  end

  # GET /fish/new
  def new
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish or /fish.json
  def create
    @fish = Fish.new(fish_params)

    respond_to do |format|
      if @fish.save
        format.html { redirect_to @fish, notice: "Fish was successfully created." }
        format.json { render :show, status: :created, location: @fish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fish/1 or /fish/1.json
  def update
    respond_to do |format|
      if @fish.update(fish_params)
        format.html { redirect_to @fish, notice: "Fish was successfully updated." }
        format.json { render :show, status: :ok, location: @fish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1 or /fish/1.json
  def destroy
    @fish.destroy
    respond_to do |format|
      format.html { redirect_to fish_index_url, notice: "Fish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fish_params
      params.require(:fish).permit(:name, :latin_name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_signed_in

  def index
  end

  def check_signed_in
    redirect_to fishing_areas_path if signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/helpers/fish_wardens_helper.rb
module FishWardensHelper
end

app/helpers/fisheries_helper.rb
module FisheriesHelper
end

app/helpers/fishing_areas_helper.rb
module FishingAreasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/countries/_form.html.erb
<%= simple_form_for(@country) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/countries/_list_countries.html.erb
<div class="list-group">
  <% countries.each_with_index do |country,i| %>
    <% if i%2 == 0 %>
      <%= link_to country.name, country , class: "list-group-item list-group-item-action list-group-item-light" %>
    <% else %>
      <%= link_to country.name, country , class: "list-group-item list-group-item-action list-group-item-dark" %>
    <% end %>
  <% end %>
</div>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<div class="container">
  <h1>Countries</h1>
  <%= render 'countries/list_countries', countries: @countries %>
  <br>
  <% if current_user.admin %>
    <div class="d-flex justify-content-center">
      <%= link_to 'New Country', new_country_path, class:'btn btn-outline-primary'%>
    </div>
  <% end %>
</div>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>  <%= @country.name %> </h1>
    </div>
    <% if current_user.admin %>
      <div class="col">
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to 'Edit', edit_country_path(@country), class: "btn btn-primary" %>
          <%= link_to 'Destroy', @country, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        </div>
      </div>
    <% end %>
  </div>
  <br>

  <div class="list-group" >
    <%= link_to 'Locations', country_locations_path(@country), class: "list-group-item list-group-item-action list-group-item-light", style:"font-size:1.5em;text-align:center;" %>
    <%= link_to 'Fisheries', country_fisheries_path(@country), class: "list-group-item list-group-item-action list-group-item-dark ", style:"font-size:1.5em;text-align:center" %>

  </div>


  <% if current_user.admin %>
    <%= link_to 'Edit', edit_country_path(@country) %>
  <% end %>
  <%= link_to 'Back', countries_path %>
</div>