config/routes.rb
Rails.application.routes.draw do

  resources :fish

  resources :licence_issuers do
    resources :fish_wardens
  end

  resources :countries do
    resources :locations
    resources :fisheries
  end

  resources :body_of_waters

  resources :fishing_areas do
    resources :comments
  end

  devise_for :users
  #root to: 'home#index'
  root to: 'fishing_areas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_of_water.rb
class BodyOfWater < ApplicationRecord
enum water_type: [ :river, :lake, :stream, :canal, :sea ]
validates :water_type, presence:true
validates :name, presence:true, length:{maximum: 100}
has_many :fishing_areas

def to_label
  "#{name} #{water_type}"
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :fishing_area
  validates :body, presence:true, length:{maximum: 255}

  
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, length: {minimum:3},presence: true, uniqueness: true
  has_many :fishin_areas
  has_many :locations, dependent: :destroy
  has_many :fisheries, dependent: :destroy


  def to_label
    "#{name}"
  end
end

app/models/fish.rb
class Fish < ApplicationRecord
  has_and_belongs_to_many :fishing_areas
  validates :name, length: {minimum:3,maximum:100},presence: true, uniqueness: true
  validates :latin_name, length: {minimum:3,maximum:100},presence: true, uniqueness: true
  validates :description, length: {maximum:1024}
end

app/models/fish_warden.rb
class FishWarden < ApplicationRecord
  validates :phone, length: {minimum:9, maximum:15},presence: true, uniqueness: true
  validates :name, length: {minimum:1},presence: true
  belongs_to :licence_issuer
end

app/models/fishery.rb
class Fishery < ApplicationRecord
  belongs_to :country
  has_many :fishing_areas
  belongs_to :licence_issuer
  validates :name, length: {minimum:3},presence: true, uniqueness: true

  def to_label
    "#{name}"
  end
end

app/models/fishing_area.rb
class FishingArea < ApplicationRecord
  belongs_to :user
  belongs_to :body_of_water
  belongs_to :country
  belongs_to :location
  belongs_to :fishery
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :fish
  #active storage
  has_one_attached :thumbnail, dependent: :detach
  #if user did not attach image
  after_commit :add_default_thumbnail, on:[:create, :update]

  validates :name, length: {minimum:3},presence: true, uniqueness: true

  self.per_page=9

  def optimized_image(image,x,y)
    image.variant(resize_to_fill: [x, y]).processed
  end

  private

  def add_default_thumbnail
    unless thumbnail.attached?
      self.thumbnail.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.jpg")), filename: 'default.jpg' , content_type: "image/jpg")
    end
  end

end

app/models/licence_issuer.rb
class LicenceIssuer < ApplicationRecord
  validates :name, length: {minimum:3},presence: true, uniqueness: true
  has_many :fisheries
  has_many :fish_wardens

  def to_label
    "#{name}"
  end

end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, length: {minimum:3, maximum:100},presence: true
  validates :province, length: {minimum:3, maximum:100},presence: true
  has_many :fishing_areas
  belongs_to :country

  def to_label
    "#{name}, #{province}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fishing_areas
  has_many :comments, dependent: :destroy

  def username
    email.split("@")[0].capitalize
  end

  def to_label
    username
  end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :set_fish, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :is_admin!, except: [:index, :show]

  # GET /fish or /fish.json
  def index
    @fish = Fish.all
  end

  # GET /fish/1 or /fish/1.json
  def show
  end

  # GET /fish/new
  def new
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish or /fish.json
  def create
    @fish = Fish.new(fish_params)

    respond_to do |format|
      if @fish.save
        format.html { redirect_to @fish, notice: "Fish was successfully created." }
        format.json { render :show, status: :created, location: @fish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fish/1 or /fish/1.json
  def update
    respond_to do |format|
      if @fish.update(fish_params)
        format.html { redirect_to @fish, notice: "Fish was successfully updated." }
        format.json { render :show, status: :ok, location: @fish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1 or /fish/1.json
  def destroy
    @fish.destroy
    respond_to do |format|
      format.html { redirect_to fish_index_url, notice: "Fish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fish_params
      params.require(:fish).permit(:name, :latin_name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_signed_in

  def index
  end

  def check_signed_in
    redirect_to fishing_areas_path if signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/helpers/fisheries_helper.rb
module FisheriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/_flash_alerts.html.erb
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> alert-dismissible fade show  role="alert">
      <h6><strong>  <%= message %>  </strong></h6>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Fish Find</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>


    </ul>



    <ul class="navbar-nav ml-auto">
      <% if current_user %>

      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Explore
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

          <%= link_to 'Bodies of water', body_of_waters_path, class:"dropdown-item" %>
          <%= link_to 'Countries', countries_path, class:"dropdown-item" %>
          <%= link_to 'Licence Issuers', licence_issuers_path, class:"dropdown-item" %>
          <%= link_to 'Target fish species', fish_index_path, class:"dropdown-item" %>


          </div>
      </li>



        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to 'New Fishing Area', new_fishing_area_path, class:"dropdown-item" %>

            <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", destroy_user_session_path, class:'dropdown-item', method: :delete %>
            </div>
        </li>
    <% else %>
        <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class:'nav-link' %>
        </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishFind</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_alerts' %>
    <%= yield %>
  </body>
</html>